# The repository owner's GitHub Sponsors account; no third-party payee is configured.
# A public Sponsors listing and the repository Sponsorships setting are prerequisites.
# This file does not enroll an account, create a payment account or change the license.
github: [paulkakell]
